# Generated by Django 2.1.5 on 2019-02-09 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('email_address', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, default='', max_length=255)),
                ('lastname', models.CharField(blank=True, default='', max_length=255)),
                ('referenced_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=225)),
                ('user_readonly', models.BooleanField()),
                ('group_readonly', models.BooleanField()),
                ('group', models.ForeignKey(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), on_delete=django.db.models.deletion.SET_DEFAULT, to='auth.Group')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mails.Folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.TextField(blank=True, default='')),
                ('recivedate', models.DateTimeField()),
                ('originfile', models.CharField(blank=True, max_length=255, null=True)),
                ('mailtype', models.CharField(choices=[('MIME', 'MIME'), ('AES_ENCRYPTED', 'AES encrypted'), ('RSA_ENCRYPTED', 'RSA encrypted')], default='MIME', max_length=32)),
                ('bcc', models.ManyToManyField(blank=True, related_name='bcc_relations', to='mails.Contact')),
                ('cc', models.ManyToManyField(blank=True, related_name='cc_relations', to='mails.Contact')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mails.Folder')),
                ('mail_from', models.ManyToManyField(related_name='from_relations', to='mails.Contact')),
                ('to', models.ManyToManyField(related_name='to_relations', to='mails.Contact')),
            ],
        ),
    ]
